export interface CarePlan {
    patientName: string;
    summary: string; // concise layman summary (max 2 sentences)
    medications: Medication[];
    redFlags: string[]; // List of 2-3 specific symptoms to watch out for
    dietaryTips: string[]; // List of 2-3 specific diet/lifestyle actionable tips (e.g. "Eat beetroot")
    followUp: string; // e.g., "7 days" or "1 month"
}

export interface Medication {
    name: string;
    dosage: string; // e.g. "500mg"
    schedule: {
        morning: boolean;
        afternoon: boolean;
        night: boolean;
    };
    instruction: string; // e.g. "After food"
    type: "Tablet" | "Syrup" | "Injection" | "Other";
    purpose: string; // e.g. "For blood pressure" (generated by AI)
}
